### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jinjinwa** [lin-xin/vue-manage-system#10]
建议作者把项目名称增加vue字眼或者描述。相信会有更多人搜到～

**Comment by lin-xin** [comment]
@jinjinwa 嗯，谢谢

**Comment by lin-xin** [comment]
@jinjinwa vue-admin 已经很多人用了，你觉得我还用这个吗？

**Comment by legendjslc** [comment]
这个建议挺好

**Comment by lin-xin** [comment]
@legendjslc 求名字 :smile:

**Comment by legendjslc** [comment]
vue-manage-system

**Comment by jinjinwa** [comment]
名字有很多，不光是可以用vueadmin啊

**Comment by Mrs-Code** [comment]
http://work.fengdb.com/  用IE浏览器访问报错，希望能尽快解决。

**Comment by huqiliang** [comment]
还好没变名 知乎上叫 manage-system 还能搜到

**Comment by irenetang1993** [comment]
您好，我想正在使用您的这套框架，我在.vue文件中加了<style scoped lang="less"> 运行的时候报错，说有很多loader没有下载。

This dependency was not found:

* !!vue-style-loader!css-loader?sourceMap!../../../node_modules/vue-loader/lib/s
tyle-rewriter?id=data-v-0e0cac89&scoped=true!less-loader!../../../node_modules/v
ue-loader/lib/selector?type=styles&index=0!./Header.vue in ./src/components/comm
on/Header.vue

To install it, you can run: npm install --save !!vue-style-loader!css-loader?sou
rceMap!../../../node_modules/vue-loader/lib/style-rewriter?id=data-v-0e0cac89&sc
oped=true!less-loader!../../../node_modules/vue-loader/lib/selector?type=styles&
index=0!./Header.vue

但是我在package.json的devDependencies中看到loaders都下载了呀，package.json和您的一样

**Comment by zhangly912** [comment]
为什么select选择框选择的内容不会显示在select上面呢？

**Comment by lin-xin** [comment]
@zhangly912 怎么不会？

**Comment by zhangly912** [comment]
就是select框里面选择一个值之后，如何显示选中状态呢。

**Comment by lin-xin** [comment]
@zhangly912 你是发现我的demo不生效呢？还是你自己写的选择器不生效啊？是你的话请贴代码啊

**Comment by zhangly912** [comment]
@lin-xin 你的demo里面不是有那个baseForm那一块吗？就是那里的select框，我选择一个之后，select里面的那个input还是显示请选择，而没有显示我选择的那个option。

**Comment by lin-xin** [comment]
@zhangly912 你用什么浏览器呢？我这边正常啊。

**Comment by zhangly912** [comment]
@lin-xin  所有浏览器都这样  我也觉得很奇怪  都说只要配置model就好，我这边就是死活那个组件里面的input没有值啊。而且我看官网那些demo显示是对的，但是点击那个在线运行，也是不会显示选择的匹配项。。。

**Comment by lin-xin** [comment]
@zhangly912 我不知道你那边怎么回事，但是我刚试了点官网那个在线运行，确实能显示选择那项啊

**Comment by zhangly912** [comment]
@lin-xin  心好塞，谢谢你了。

**Comment by zhangly912** [comment]
@lin-xin 发现问题了，你的package.json是不是没有更新？因为ui版本需要跟新到最新。官网升级有说明这是个兼容bug

**Comment by lin-xin** [comment]
@zhangly912 嗯，我升级element到1.3.1版本就出现该问题了。该issue用于提建议，这些bug反馈将会被删除，如有问题，重开新的issue，谢谢。
