### ISSUE TITLE
在子页面如何关闭当前标签？

### ISSUE THREAD

**Issue by xiaolv899** [lin-xin/vue-manage-system#106]
当前子页面代码已经执行完毕；需要自动关闭当前标签页，有没有全局的方法调用？

**Comment by xiaolv899** [comment]
关闭当前标签页，并返回前一个标签（不是按顺序的最后一个标签页）

**Comment by fanxl12** [comment]
利用bus去tags来调关闭的方法就可以

**Comment by lin-xin** [comment]
新版本里添加了 close_current_tags 事件去关闭。 bus.$emit('close_current_tags ')
