### ISSUE TITLE
用户授权怎么处理

### ISSUE THREAD

**Issue by shuaibird** [lin-xin/vue-manage-system#11]
有个问题想不明白，用户鉴权和授权怎么处理？即用户没登录的状态只能访问登陆页，不能进入系统内部

**Comment by lin-xin** [comment]
用路由钩子
`router.beforeEach((to,from,next)=>{
    if(to.path !== '/login'){    // 如果不是跳转到登录页面则进行检测登录状态
        if(!checkLogin()){      // 检测未登录则跳转到登录页面
            next({'path':'/login'});
        }else{
            next();
        }
    }else{
        next();
    }
})`
