### ISSUE TITLE
为什么会报下面的这个错误 ？

### ISSUE THREAD

**Issue by Jaction** [lin-xin/vue-manage-system#12]
我直接下载后cnpm install 然后npm run dev 就报错了
![qq 20170325001254](https://cloud.githubusercontent.com/assets/17811893/24303194/1a07162a-10f0-11e7-85eb-bc296699603a.png)
  
看看这个是什么问题

**Comment by lin-xin** [comment]
这是缺少了下面的依赖，用npm install，cnpm的有的不全

**Comment by Jaction** [comment]
好的 那就用npm  为什么用cnpm不全呢？什么问题导致的

**Comment by lin-xin** [comment]
cnpm是国内镜像，有的时候还没把npm的同步过来

**Comment by Jaction** [comment]
我刚刚也npm intall 
![image](https://cloud.githubusercontent.com/assets/17811893/24320664/a1d2211a-1174-11e7-9d0b-cb71f6b56f65.png)
![image](https://cloud.githubusercontent.com/assets/17811893/24320666/b6d69fc8-1174-11e7-8dad-e951d25912e6.png)

**Comment by Jaction** [comment]
还是报同样的错

**Comment by lin-xin** [comment]
@Jaction 我认为还是要多尝试一下吧，先删除掉 node_modules 再重新 npm install ,或者看看是否npm 版本低，还是npm之前就已经配置过 npm config set registry ... 重新配置看看？

**Comment by lin-xin** [comment]
@Jaction 发现你这个问题只要执行 npm i vue-simplemde vue-quill-editor -S 就可以。是这个两个插件没装上。
