### ISSUE TITLE
style标签里@import '~@/.../index.css'报错

### ISSUE THREAD

**Issue by liupei1995** [lin-xin/vue-manage-system#129]
在style标签里引入使用@import ‘~@/...’ 会提示文件找不到
路径都是对的，下方有截图
我用vue-cli创建的项目是可以的
所以想问下是缺少什么模块依赖吗
麻烦了
![qq 20180913103234](https://user-images.githubusercontent.com/21356797/45463861-6f6cee80-b740-11e8-88e4-b6059d148547.png)
![qq 20180913103244](https://user-images.githubusercontent.com/21356797/45463862-6f6cee80-b740-11e8-857b-c336ba23fee1.png)
![qq 20180913103255](https://user-images.githubusercontent.com/21356797/45463863-6f6cee80-b740-11e8-8011-08e5e14a630c.png)

**Comment by lin-xin** [comment]
你的这个~@是配置的别名，我这个配置文件里没有配置别名。你要用的话需要加上去，你可以参考你之前可以的配置文件，添加到我这里的配置文件即可

**Comment by liupei1995** [comment]
> 你的这个~@是配置的别名，我这个配置文件里没有配置别名。你要用的话需要加上去，你可以参考你之前可以的配置文件，添加到我这里的配置文件即可

我配置了别名@，然后网上查找答案说在style标签里引用别名需要加上~，但我加了还是提示找不到，有点崩溃

**Comment by lin-xin** [comment]
@liupei1995 我来试试

**Comment by liupei1995** [comment]
> @liupei1995 我来试试

好的，谢谢了

**Comment by lin-xin** [comment]
是使用了postcss-import导致的，postcss-import并不会直接去识别~@
把.postcssrc.js文件里的 "postcss-import": {} 去掉然后重启试试。

**Comment by liupei1995** [comment]
> 是使用了postcss-import导致的，postcss-import并不会直接去识别~@
> 把.postcssrc.js文件里的 "postcss-import": {} 去掉然后重启试试。

可以了，非常感谢。
但发现一个问题就是：如果去掉这个属性，那在style @import css文件，就会变成全局变量（笑哭）

**Comment by lin-xin** [comment]
import 本来就不会加上 scoped，你可以这样写：
`<style scoped src="@/assets/index.css">`
就是局部了

**Comment by liupei1995** [comment]
> import 本来就不会加上 scoped，你可以这样写：
> `<style scoped src="@/assets/index.css">`
> 就是局部了

恩恩，在网上找到答案了，非常感谢
