### ISSUE TITLE
http://work.omwteam.com/ IE访问报错

### ISSUE THREAD

**Issue by Mrs-Code** [lin-xin/vue-manage-system#13]
http://work.omwteam.com/ 用IE浏览器访问报错，希望能尽快解决。我的是IE11不过IE里头都不行。

**Comment by lin-xin** [comment]
@Mrs-Code 之前确实没测试IE ，现在发现确实是，用到 Promise 的地方都在 IE 中不兼容，包括 Vuex 也是一样。看了有些人的项目也是，我在找解决办法。

**Comment by lin-xin** [comment]
已经兼容IE，不过里面的 富文本、markdown、图片裁剪 暂不兼容。
解决方案为引入 babel-polyfill
