### ISSUE TITLE
运行项目时报错

### ISSUE THREAD

**Issue by Zyangyi1995** [lin-xin/vue-manage-system#139]
![Uploading 1544409445(1).jpg…]()

他会报错template模板里的transtion-group标签下不要使用v作为索引建,我百度也找不出这个问题,只能来问大佬们了- -

**Comment by Zyangyi1995** [comment]
![1544409445 1](https://user-images.githubusercontent.com/43595720/49707831-0bd35e00-fc68-11e8-8a04-2ce0c308149e.jpg)
![1544409458 1](https://user-images.githubusercontent.com/43595720/49707834-0c6bf480-fc68-11e8-8b26-58122d6e85a8.jpg)

**Comment by cdk-king** [comment]
我的也是，貌似是v-for 的 index 出了问题

**Comment by dj20150624** [comment]
把这个注释掉，或者删除路由即可正常运行

**Comment by LiPengFei1989** [comment]
这个问题出现的原因: <transition-group>必须指定key属性,但是v-for的索引并不是合法的key值

1. 在组件的JavaScript部分, 将循环变量todo、duing和done下的每个元素添加一个id属性
2. 将<transition-group>标签内的循环元素的key改成item.id, 例如: :key="item.id"
3. 搞定

**Comment by LiPengFei1989** [comment]
这个问题出现的原因: transition-group必须指定key属性,但是v-for的索引并不是合法的key值

**Comment by lin-xin** [comment]
这个问题在最新版本里已修复
