### ISSUE TITLE
npm run build极其慢

### ISSUE THREAD

**Issue by aslinwang** [lin-xin/vue-manage-system#14]
![image](https://cloud.githubusercontent.com/assets/2310005/24500076/a7a9d2ee-1576-11e7-8f06-d64bf1ec3ae8.png)

请问下如何解决？

**Comment by lin-xin** [comment]
@aslinwang webpack会因为项目大小影响构建速度。网上的解决方案是 把不常变动的js独立构建出来，可以看 https://zhuanlan.zhihu.com/p/21748318 这篇文章。我自己也在尝试。

**Comment by lin-xin** [comment]
@aslinwang 新的配置已经更新，构建速度以提高，具体解决方案可见：https://github.com/lin-xin/blog/issues/10
