### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by qpb** [lin-xin/vue-manage-system#141]
extract:util: sill extract json-schema-traverse@0.4.1
      throw er; // Unhandled 'error' event

extract:chalk: sill extract chalk@1.1.3
      throw er; // Unhandled 'error' event

类似报这种错误，是需要安装依赖版本号有问题么。
本机node版本8.9.1、npm版本6.4.1

**Comment by lin-xin** [comment]
npm 安装失败可以使用cnpm或yarn
