### ISSUE TITLE
npm install 报错下不了包

### ISSUE THREAD

**Issue by zxbking** [lin-xin/vue-manage-system#144]
sha512-x95Td74QcvICAA0+qERaVkRpTGKyBHHYdwL2LXZm5t/gBtCB9KQSO/0zQgSTYEV1p0WcvSg79TLNPSvd5IDJMQ==

主要是这个下不了。这里查了下是npm的版本问题。主动降到4.0
npm -g install npm@4 
再执行npm install就可以了

**Comment by lin-xin** [comment]
npm有问题的话，还可以使用cnpm 或 yarn 安装
