### ISSUE TITLE
为什么我在切换路由的时候js之执行一次

### ISSUE THREAD

**Issue by 547437352** [lin-xin/vue-manage-system#15]
作者你好！非常感谢你的贡献，进期正好要做后台系统，厌烦了以前的模式，想引进新技术！首先说下我是小白，如果提的问题是element或者vue本身的问题请谅解：

 1.当我在侧边栏切换的时候发现js实际上执行了一次！如我在BaseTable组件中console.log(123123)，发现只有当进入主页面的时候执行一次，但是再次切换到form组件不会执行！这样是很糟糕的，我在想是不是我在组件中写的ajax也只是在进入页面的时候执行一次，再切换的时候就不执行了！

**Comment by lin-xin** [comment]
@547437352 你的意思是说，在table组件写js，进到form组件不会执行table中的js吗？如果是这样，那肯定是不会执行的啊

**Comment by 547437352** [comment]
@lin-xin   说错了！是再次进入basetable组件！![qq 20170331100255](https://cloud.githubusercontent.com/assets/13287603/24533291/5126532e-15f9-11e7-99d6-5d4d967b18e3.png)比如我basetable里面打印了一个东西！只有第一次进来的时候执行一次，在切换到别的组件在切换到basetable，就不执行了

**Comment by lin-xin** [comment]
@547437352 你不能这样写。这样子打包之后只会加载一次这个js文件。你要写在 created(){..} 或者 mounted(){...} 里，每次重新进入才会在执行 console 。因为这是单页面应用，你切换路由不会重新加载js的，所以只会打印一次。

**Comment by 547437352** [comment]
@lin-xin   这样写真的行了
![qq 20170331103210](https://cloud.githubusercontent.com/assets/13287603/24533942/7511613a-15fd-11e7-87bc-2a4494617ea1.png)   ，因为我之前没用模块化也是用的vue1.x和router，只要在ready钩子中写再次进入就会执行！说到底还是不熟悉！    拿在这些组件中我们写业务逻辑ajax还是在mounted钩子写是吧！

**Comment by lin-xin** [comment]
嗯，这是vue的知识，建议多阅读几遍文档，我自己也是看了几遍了，每看一遍都会理解更多

**Comment by 547437352** [comment]
能力还不足，进阶的地方有有好些看不太懂的！ 再次感谢

**Comment by 547437352** [comment]
![fenye](https://cloud.githubusercontent.com/assets/13287603/24541137/cc2aa226-1628-11e7-832a-08de04419904.png)  分页我修改成完整版的！
![123123](https://cloud.githubusercontent.com/assets/13287603/24541184/f3fe6fd0-1628-11e7-95d8-90da8123dfa7.png)   

  点击切换不同的分页的时候处理函数，我这么写！如果我请求过来数据的时候手动赋值data，发现表格还是死数据没有反应！

还有一点：

我数据currentPage4 在data中写成了1，当我切换到第二页的时候，发现打印出来的不是2，还是1，一直是1，这个currentPage4不是根据页数变化的吗？如果不变化，第二页的时候怎么网接口传递页码

**Comment by 547437352** [comment]
@lin-xin

**Comment by lin-xin** [comment]
@547437352 在methods中写了handleCurrentChange这个方法了没有，改变页码的时候在这个方法里把页码赋值给currentPage4，详情看element官方文档。

**Comment by 547437352** [comment]
![image](https://cloud.githubusercontent.com/assets/13287603/24541930/413769e8-162c-11e7-86f4-c41a3c532b87.png)
就是在methods中写的！

**Comment by 547437352** [comment]
@lin-xin

**Comment by lin-xin** [comment]
@547437352 你看文档了没有呢，这样写的
![Uploading QQ截图20170331161147.png…]()

**Comment by lin-xin** [comment]
@547437352 看文档了吗，是这样写的
![qq 20170331161147](https://cloud.githubusercontent.com/assets/13494930/24542147/17117266-162d-11e7-8fad-9d90e56dee4f.png)

**Comment by 547437352** [comment]
@lin-xin   嗯我找到了，页面的问题我找到了，关于手动赋值data，view不更新的问题，您有什么处理方式吗

**Comment by 547437352** [comment]
@lin-xin  您有遇到这个问题吗？

**Comment by lin-xin** [comment]
没遇过，vue是双向绑定的，修改了data 就会视图也会更新，你不更新，估计是哪里写错。对着文档查查问题吧

**Comment by 547437352** [comment]
@lin-xin    说出来很丢人，this指向错误，我在setTimeout中用this，this是window
![1233](https://cloud.githubusercontent.com/assets/13287603/24546679/f89de2da-163e-11e7-9ed4-9a95e8ee5bea.png)  这样就好了
