### ISSUE TITLE
请问怎么断点调试或者和后端对接

### ISSUE THREAD

**Issue by 547437352** [lin-xin/vue-manage-system#16]
1.比如我现在我dev以后，点击登陆的按钮回执行自己的逻辑，我发现我在浏览器中找不到这行代码
2，还有我整个项目都要传到git上吗太大了，还是我需要build后只把dist给后台，可是dist都是压缩后的代码，能不让他压缩build后就像传统的页面一样，css和js都是引入的浏览器明显能看到代码

**Comment by 547437352** [comment]
@lin-xin

**Comment by lin-xin** [comment]
@547437352 1、vue-devtool调试工具。2、只需上传dist即可。
