### ISSUE TITLE
下载最新版本发布后发现没有进行懒加载处理

### ISSUE THREAD

**Issue by thomas2010** [lin-xin/vue-manage-system#161]
发布后的index.html页面代码是这样的
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><link rel=stylesheet href=http://at.alicdn.com/t/font_830376_qzecyukz0s.css><title>vue-manage-system</title><script src=https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js></script><link rel=stylesheet href=https://unpkg.com/element-ui@2.3.7/lib/theme-chalk/index.css><script src=https://cdn.bootcss.com/vue/2.5.22/vue.min.js></script><script src=https://cdn.bootcss.com/vue-router/3.0.1/vue-router.min.js></script><script src=https://cdn.bootcss.com/axios/0.18.0/axios.min.js></script><script src=https://unpkg.com/element-ui@2.3.7/lib/index.js></script><link href=css/Dashboard.css rel=prefetch><link href=css/Home.css rel=prefetch><link href=css/chunk-17ff363c.css rel=prefetch><link href=css/chunk-1b886a23.css rel=prefetch><link href=css/chunk-244b88a2.css rel=prefetch><link href=css/chunk-3c0c846a.css rel=prefetch><link href=css/chunk-3fcbd12e.css rel=prefetch><link href=css/chunk-4abf228e.css rel=prefetch><link href=css/chunk-5c0d1206.css rel=prefetch><link href=css/chunk-6d4d5a6c.css rel=prefetch><link href=css/chunk-9780dcf8.css rel=prefetch><link href=css/chunk-9bc617e2.css rel=prefetch><link href=css/chunk-d5224c00.css rel=prefetch><link href=css/chunk-e1f9e4d0.css rel=prefetch><link href=css/chunk-f1225e32.css rel=prefetch><link href=js/Dashboard.js rel=prefetch><link href=js/Home.js rel=prefetch><link href=js/chunk-17ff363c.js rel=prefetch><link href=js/chunk-1b886a23.js rel=prefetch><link href=js/chunk-244b88a2.js rel=prefetch><link href=js/chunk-2d230500.js rel=prefetch><link href=js/chunk-3c0c846a.js rel=prefetch><link href=js/chunk-3fcbd12e.js rel=prefetch><link href=js/chunk-4abf228e.js rel=prefetch><link href=js/chunk-5c0d1206.js rel=prefetch><link href=js/chunk-6d4d5a6c.js rel=prefetch><link href=js/chunk-9780dcf8.js rel=prefetch><link href=js/chunk-9bc617e2.js rel=prefetch><link href=js/chunk-d5224c00.js rel=prefetch><link href=js/chunk-e1f9e4d0.js rel=prefetch><link href=js/chunk-f1225e32.js rel=prefetch><link href=css/app.css rel=preload as=style><link href=js/app.js rel=preload as=script><link href=js/chunk-vendors.js rel=preload as=script><link href=css/app.css rel=stylesheet></head><body><noscript><strong>We're sorry but vms doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=js/chunk-vendors.js></script><script src=js/app.js></script></body></html>

**Comment by lin-xin** [comment]
这肯定不是。。我都没用 jQuery
