### ISSUE TITLE
关于Table 中默认padding怎么修改

### ISSUE THREAD

**Issue by 547437352** [lin-xin/vue-manage-system#17]
element中的table默认padding，感觉太大了，
![qq 20170405153504](https://cloud.githubusercontent.com/assets/13287603/24694715/942b96e6-1a15-11e7-9d15-c8159e59dba5.png) 明明可以在一行显示的，查看了element的文档没有发现有控制padding的api！
![qq 20170405153521](https://cloud.githubusercontent.com/assets/13287603/24694754/b8c6f6da-1a15-11e7-8807-dc9020d015c8.png)    也尝试了在elemet issues提问的同样问题的解决方案，但是还是不起作用：http://jsfiddle.net/hqvnwsdk/

**Comment by 547437352** [comment]
@lin-xin

**Comment by lin-xin** [comment]
你写样式覆盖，不要加上作用域 scoped ,因为html是由js生成的，作用域不起作用

**Comment by 547437352** [comment]
已经成功了 @lin-xin
