### ISSUE TITLE
el-upload组件上传图片

### ISSUE THREAD

**Issue by 547437352** [lin-xin/vue-manage-system#18]
@lin-xin    现在用 el-upload组件上传图片，但是发现选择图片后立即上传，但是需求是这样的
![qq 20170406162904](https://cloud.githubusercontent.com/assets/13287603/24744897/3224df26-1ae6-11e7-9919-e39da2d1ef99.png)
我需要手动上传图片，可是发现如果设置了auto-upload为false的时候，那么就得不到预览图，查看了element的issues，可以自动获取图片的地址然后手动赋值src，可是当手动上传的时候发现发不出请求！
请问这个有解决方案吗
![qq 20170406163232](https://cloud.githubusercontent.com/assets/13287603/24745080/e58f40d8-1ae6-11e7-928a-9e5858db9a79.png)
![qq 20170406163344](https://cloud.githubusercontent.com/assets/13287603/24745094/ee44b424-1ae6-11e7-815c-01c148c883c7.png)

**Comment by lin-xin** [comment]
我认为你应该去element提issue
