### ISSUE TITLE
怎么配置线上环境接口地址和测试环境接口地址

### ISSUE THREAD

**Issue by gankehuang** [lin-xin/vue-manage-system#181]

**Comment by lin-xin** [comment]
process.env.NODE_ENV === 'development' ? '测试地址' : '线上地址'

**Comment by wangwentao123** [comment]
怎样找不到dev 本地启动的端口啊

**Comment by lin-xin** [comment]
@wangwentao123 看看[vue-cli3配置文档](https://cli.vuejs.org/zh/config/#devserver)吧
