### ISSUE TITLE
sidebar导航栏icon更换使用iconfont图标遇到的问题

### ISSUE THREAD

**Issue by mingxuan0624** [lin-xin/vue-manage-system#185]
1. 我是用iconfont生成自己的图标，并使用font class生成连接;
2. 我把index中的https://at.alicdn.com/t/font_830376_qzecyukz0s.css替换成我的连接地址；
3. 然后我在siderbar.vue文件中，更改icon: "el-icon-lx-home"这个，填入我的icon名称，但是页面不显示。前面没有‘el-’.请问我是哪里写错了么？谢谢！

**Comment by lin-xin** [comment]
还少了一步，在你的css中要加上这个，声明你的图标使用的字体
```
[class*=" el-icon-lx"], [class^=el-icon-lx] {
        font-family: lx-iconfont!important;
}
```
