### ISSUE TITLE
跨域报错

### ISSUE THREAD

**Issue by Mrbei1** [lin-xin/vue-manage-system#186]
为何修改vue.config.js =>proxy ，设置跨域，调用服务器接口仍报跨域。

**Comment by Mrbei1** [comment]
跨域

**Comment by lin-xin** [comment]
改完重新run一下，还不行就是设置错了

**Comment by Mrbei1** [comment]
run了，还是不行。config配置：module.exports = {
    baseUrl: './',
    assetsDir: 'static',
    outputDir: 'dist',
    filenameHashing: true,
    publicPath:'',
    //publicPath: process.env.NODE_ENV === 'development' ? 'http://47.92.220.18:9090' : '/',
    productionSourceMap: false,
    devServer: {
        host: 'localhost',
        port: 8080,
        https: false,
        //以上的ip和端口是我们本机的;下面为需要跨域的
        proxy: {//配置跨域
            '/api': {
                target: 'http://47.92.220.18:9090',
                //ws: true,
                changOrigin: true,//允许跨域
                pathRewrite: {
                    '^/api': ''
                }
            }

        }
    }
}

**Comment by lin-xin** [comment]
'/api'是匹配这个开头的请求，你的请求路径有没有带这个

**Comment by Mrbei1** [comment]
嗯，好的，我再去看看，谢谢你😊
