### ISSUE TITLE
clone下来之后，登陆问题

### ISSUE THREAD

**Issue by jessjava** [lin-xin/vue-manage-system#19]
首页的submitForm form 的validate返回值一直是 false。不管用户名和密码是否有值。
感觉是检测不到输入了值。或者双向绑定失败了？
导致登陆不行。

**Comment by lin-xin** [comment]
@jessjava 已经修复，之前修改一些配置导致的，可以git pull origin master试试

**Comment by jessjava** [comment]
nice ,thanks
