### ISSUE TITLE
表格筛选和排序只对当前页有效

### ISSUE THREAD

**Issue by hanaaalice** [lin-xin/vue-manage-system#192]
首先感谢作者的分享
问题描述：BaseTable.vue：使用element的el-table时，对表格进行查询或者对某一列数据进行降序或升序排列，只对当前页的data有效，显示一页的筛选和排序结果未免有点反人类了，是否有更好的方法能使查询或排序操作对整个tableData有效并且能分页显示呢？
我对查询内容的解决方法是在computed中判断当前是否在搜索状态中，从而改变返回的表格data
代码如下：
```javascript
tableDataFinal() {
  if (this.search_not) {
    return this.tableData
  }else{
  return this.tableDataBegin.filter( data => {
    if ((data.usertitle.toLowerCase().includes(this.filters_last.toLowerCase()))
    && (data.name.toLowerCase().includes(this.filters_first.toLowerCase()) 
    || data.id.toLowerCase().includes(this.filters_first.toLowerCase()))) {
      return data
    }
  })
  }
}
```
tableDataBegin是所有的数据；tableData是处理后分页的数据
当然，我最开始获取数据时没有加入分页条件，返回的是整个tableDataBegin。这样获取的内容又没有分页，只好隐藏了分页条，显得很鸡肋，同时排序用的是el-table自带的，也不知道如何解决，所以想请教一下作者，多谢~

**Comment by swuecho** [comment]
表格我用这个 https://www.ag-grid.com/ 更好一点。
