### ISSUE TITLE
这个后台管理框架，可以搭配自己写的API接口吗？

### ISSUE THREAD

**Issue by kuwo2016** [lin-xin/vue-manage-system#193]
我自己用nodejs写了一套api接口的，可以搭配这个后台管理框架使用吗，接入规范是怎样的，有没有文档或案例参考，谢谢！

**Comment by lin-xin** [comment]
/api/index.js 里已经有一个接口了，跟着那个写就可以了，改成你的接口地址即可

**Comment by lzzhanglin** [comment]
> /api/index.js 里已经有一个接口了，跟着那个写就可以了，改成你的接口地址即可

作者你好，我的毕设前端模板就是用的这个，我就自己改了一写业务页面，哈哈哈谢谢作者

**Comment by GodQ** [comment]
utils/request.js就相当于python的requests库了，直接在api/index.js里面添加调用后端的方法或者在api里面创建新的js文件写业务后端调用函数都可以，很简单。这个框架确实短小精悍，👍
