### ISSUE TITLE
百度搜索不到类似问题，我也没有这个属性showClose，找不到原因

### ISSUE THREAD

**Issue by hohnworld** [lin-xin/vue-manage-system#201]
Invalid prop: type check failed for prop "showClose". Expected Boolean, got String with value "false".

**Comment by lin-xin** [comment]
这个错误就是说你有个 show-close 的属性应该传布尔值，你却传了个字符串 “false”，这你要自己找你项目中的 问题了。。。

**Comment by hohnworld** [comment]
好的，谢谢
