### ISSUE TITLE
路由

### ISSUE THREAD

**Issue by YeZhiqiuSev** [lin-xin/vue-manage-system#21]
![image](https://cloud.githubusercontent.com/assets/18155748/25060360/d28d345c-21cd-11e7-9910-8f18e7ccc8b2.png)
请问一下，这个子路由的访问路径不应该是/readme/basetable么？为什么这样访问不到，反而不要父路径是对的？

**Comment by lin-xin** [comment]
@YeZhiqiuSev 如果这样写 path : 'basetable' ,就 需要这样 /readme/basetable 访问，这样写就相对父路径。
