### ISSUE TITLE
Cannot read property 'querySelector' of undefined"

### ISSUE THREAD

**Issue by chenloo** [lin-xin/vue-manage-system#211]
运行出现这个问题，如何解决  Cannot read property 'querySelector' of undefined"

**Comment by lujiannt** [comment]
同出現這個問題

**Comment by 15269156689** [comment]
出现同样的问题。。。

**Comment by guifa2015** [comment]
![image](https://user-images.githubusercontent.com/13930091/66637767-43bf7f00-ec46-11e9-8fd7-9485062e8c8b.png)
同 样问题

**Comment by lin-xin** [comment]
发现是 element ui 里table组件设置了 height属性导致的，已在最新版本中修复了
