### ISSUE TITLE
样式修改无效

### ISSUE THREAD

**Issue by duanpf** [lin-xin/vue-manage-system#22]
比如想修改一个盒子的padding值，在谷歌控制台修改是有效的，但是在代码中修改样式不生效，使用important也不起作用。 请问博主，应该怎么做能起作用呢

**Comment by lin-xin** [comment]
加作用域 scoped

**Comment by duanpf** [comment]
已经加过了，但是不生效，现在我想修改input的padding值
<el-input placeholder="请输入您的帐号" icon="search" v-model="ruleForm.username" ></el-input>
.el-input__inner {
         padding: 3px 45px !important;
     }

但是不起作用，审查代码发现，样式根本没改变

**Comment by lin-xin** [comment]
这是js动态生成的，加scoped是不起作用的，不要加，在.vue文件里加
```
<style>
.el-input__inner {
padding: 3px 45px;
}</style>
```
亲测有效

**Comment by duanpf** [comment]
但是如果不加scoped了， 我如果在项目中使用多个input，padding值这个写的是 padding： 10px， 另外一个要写padding： 5px，都是全局设置，这样相互之间不就会影响了

**Comment by lin-xin** [comment]
那你可以加个其他类名去区别嘛

**Comment by duanpf** [comment]
嗯 好的 谢谢
