### ISSUE TITLE
全屏时折叠sidebar

### ISSUE THREAD

**Issue by swuecho** [lin-xin/vue-manage-system#220]
https://lin-xin.gitee.io/example/work/#/dashboard

以为在handleFullscreen 后面加上
```js
   if (!this.collapse) {
        this.collapseChage()
      }
```
就可以了。不过不行，可能我改的地方太多了。

**Comment by swuecho** [comment]
或者完全隐藏sidebar

**Comment by lin-xin** [comment]
```
handleFullScreen() {
    this.collapseChage();  // 加上这个，在点击全屏按钮的时候是会触发折叠的
    ......
}
```
如果是按键盘的f11，则不会触发handleFullScreen方法

**Comment by swuecho** [comment]
> ```
> handleFullScreen() {
>    this.collapseChage();  // 加上这个，在点击全屏按钮的时候是会触发折叠的
>    ......
> }
> ```
> 
> 如果是按键盘的f11，则不会触发handleFullScreen方法

这个时除非折叠变化，应该是如果处于折叠状态则不变，处于非折叠状态则触发折叠。

我看了一下 主要问题在与 sidebar 和 header 都有一个 collapse 属性，这两个属性同步的问题 导致判断是否在折叠状态有的麻烦。
