### ISSUE TITLE
icon问题

### ISSUE THREAD

**Issue by Alises** [lin-xin/vue-manage-system#224]
类似于el-icon-lx-people这种的icon，新建一个项目，把代码复制进去之后编译，为什么icon不显示呢？具体是什么问题呢

**Comment by lin-xin** [comment]
index.html还有css，复制了没

**Comment by Alises** [comment]
我的问题，所有的文件都复制了，不显示icon。然后就挨个比对了文件，自己都懵了。唯独拉下了index.html没有看。现在好了～  谢谢🙏
