### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by irenetang1993** [lin-xin/vue-manage-system#23]
您好，我想正在使用您的这套框架，我在.vue文件中加了<style scoped lang="less"> 运行的时候报错，说有很多loader没有下载。

This dependency was not found:

!!vue-style-loader!css-loader?sourceMap!../../../node_modules/vue-loader/lib/s
tyle-rewriter?id=data-v-0e0cac89&scoped=true!less-loader!../../../node_modules/v
ue-loader/lib/selector?type=styles&index=0!./Header.vue in ./src/components/comm
on/Header.vue
To install it, you can run: npm install --save !!vue-style-loader!css-loader?sou
rceMap!../../../node_modules/vue-loader/lib/style-rewriter?id=data-v-0e0cac89&sc
oped=true!less-loader!../../../node_modules/vue-loader/lib/selector?type=styles&
index=0!./Header.vue

但是我在package.json的devDependencies中看到loaders都下载了呀，package.json和您的一样

**Comment by lin-xin** [comment]
@irenetang1993 你用less，是否有安装了相关的loader，我原先里面是没装这个loader的

**Comment by irenetang1993** [comment]
装了less  和less-loader之后就好了。。我想问一下，static/css/main.css、static/css/datasource.css和static/css/color-dark.css是你自己写的样式文件还是element-ui自带的？ 如果element-ui的某些样式不满足我的需求时，我是该覆盖它还是直接修改它？

**Comment by lin-xin** [comment]
我自己写的啊，你不满足你覆盖就行了，不用去修改它。

**Comment by irenetang1993** [comment]
<el-table :data="tableData">
  <el-table-column prop="name"></el-table-column>
</el-table>

tableData {
  name: 'irene'
}
nameVariable是一个变量，value等于'name'
当我将列改为<el-table-column :prop="nameVariable"></el-table-column>时，数据就不显示了，这是为何？

**Comment by lin-xin** [comment]
请参考element官方文档
