### ISSUE TITLE
运行build的时候时间太久了

### ISSUE THREAD

**Issue by Kirito-H** [lin-xin/vue-manage-system#24]
![qq 20170419115154](https://cloud.githubusercontent.com/assets/7334679/25164867/06a45dca-2506-11e7-9654-307e1472e588.png)
build一次的时间达到了184793ms，略吓人啊。
麻烦po主有空帮忙分析下是啥原因？

另外我看之前页面是默认有引入那个vendor.dll.js的，最近更新之后发现被注释掉了，请问是什么原因呢？
@lin-xin

**Comment by lin-xin** [comment]
@Kirito-H 嗯，这里面引用太多插件了和整个element，太大了，构建的时候每次都要去压缩这些插件到一起，就很慢。之前引入了这个vendor.dll.js，构建时间确实是提高了。但是之前在一个地方有看到，所引入element的时候有报错，我前两天确实看到了在表格页会在控制台有打印了个错误，但是找不到原因。
[提高 webpack 构建 Vue 项目的速度](https://github.com/lin-xin/blog/issues/10)
