### ISSUE TITLE
可以提个问题吗？用了axios之后在谷歌浏览器为什么看不到请求

### ISSUE THREAD

**Issue by Shiyanping** [lin-xin/vue-manage-system#25]
如题

**Comment by lin-xin** [comment]
@Shiyanping 是你自己加的axios 还是我那个表格请求的数据？

**Comment by Shiyanping** [comment]
@lin-xin 就是您做的那个表格请求的数据，我看虽然是mock，但是控制台应该也会有请求吧？

**Comment by Shiyanping** [comment]
就是network里没有请求，但是数据返回是正常的

**Comment by lin-xin** [comment]
其实是没有请求的，在发出请求的时候，被mock拦截了，返回由js生成的数据。所以并没有向服务器发出请求，就不会有记录。

**Comment by Shiyanping** [comment]
哦，懂了，我看一下在哪取消mock拦截，我试试

**Comment by lin-xin** [comment]
在main.js里把引入mock的代码注释掉即可。但是就不会有数据了。

**Comment by Shiyanping** [comment]
谢谢了，我试试连我本机的接口

**Comment by Shiyanping** [comment]
@lin-xin 你好，我想问下，假如我在main.js中没有注释mock，上线之后是不是也会被拦截？

**Comment by lin-xin** [comment]
@Shiyanping 是啊，上线之后也会被拦截的。这个只是在开发阶段后台还没有数据的时候才用的，等到后台接口完成，就不需要用这个了

**Comment by Shiyanping** [comment]
好的，谢谢了，耐心

**Comment by Shiyanping** [comment]
因为这样会报错，
./src/components/page/manageContent.vue
Module not found: Error: Can't resolve 'scss-loader' in '/Users/syp/Documents/workspace/information-fe/src/components/page'
 @ ./src/components/page/manageContent.vue 3:0-219
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client babel-polyfill ./src/main.js

**Comment by lin-xin** [comment]
@Shiyanping 是否有用vue-cli，如果有，应该有配置好了loader，可以直接用啊。如果不是，那就要配置了

**Comment by Shiyanping** [comment]
@lin-xin 就是您的这个项目，这个项目应该就是用vue-cli构建的吧？

**Comment by lin-xin** [comment]
这样子，我来加个sass试试

**Comment by Shiyanping** [comment]
@lin-xin 行，谢谢了，老麻烦你

**Comment by lin-xin** [comment]
<style lang="sass">
你试试这样子。我也是出现你那个情况。改成sass，居然就可以了。
真是奇怪，我之前都是写  <style lang="scss" rel="stylesheet/scss"></style> 这样的，是可以的。
@Shiyanping

**Comment by Shiyanping** [comment]
@lin-xin 好的，我试试

**Comment by Shiyanping** [comment]
@lin-xin 牛，真的可以
