### ISSUE TITLE
项目部署之后css无法找到

### ISSUE THREAD

**Issue by YuanZhifei** [lin-xin/vue-manage-system#254]
部署在虚拟机上  Nginx 做的反向代理 
![1598623163(1)](https://user-images.githubusercontent.com/34207102/91574652-c8f47500-e979-11ea-9751-57e4fcff2b8a.jpg)

**Comment by SecinelNice** [comment]
我也是用nginx反向代理的，没有问题，看一下是不是nginx配置问题。下面是我的配置，希望对你有帮助。
`server {
  listen 80;
  root  /service/competition/dist/;
  server_name xx.yyy.xyz
  sendfile on;
  client_max_body_size 4G;

  location ~* \.(js|css|mp3|svg|png|jpg|gif|woff|ttf|eot|otf|woff2|)$ {
    add_header Cache-Control public;
    expires 1h;
    gzip_static on;
  }`

**Comment by YuanZhifei** [comment]
我再试试
