### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by oliviazhangjuan** [lin-xin/vue-manage-system#26]
### * ./src/main.js in multi ./build/dev-client babel-polyfill ./src/main.js

npm run dev 之后会出现这个错误，是为什么啊

**Comment by lin-xin** [comment]
@oliviazhangjuan 描述详细一点

**Comment by oliviazhangjuan** [comment]
git clone https://github.com/lin-xin/manage-system.git		
cd manage-system											
npm install		
npm run dev 
这一步之后终端就报这个错了

**Comment by lin-xin** [comment]
详细的报错信息

**Comment by oliviazhangjuan** [comment]
This relative module was not found:

* ./src/main.js in multi ./build/dev-client babel-polyfill ./src/main.js

**Comment by lin-xin** [comment]
看看node_modules里是不是没有  babel-polyfill

**Comment by oliviazhangjuan** [comment]
有的
This dependency was not found:

* element-ui/lib/theme-default/index.css in ./src/main.js

To install it, you can run: npm install --save element-ui/lib/theme-default/index.css


These relative modules were not found:

* ./App in ./src/main.js
* ../components/common/Home.vue in ./src/router/index.js
* ../components/page/Readme.vue in ./src/router/index.js
* ../components/page/BaseTable.vue in ./src/router/index.js
* ../components/page/VueTable.vue in ./src/router/index.js
* ../components/page/BaseForm.vue in ./src/router/index.js
* ../components/page/VueEditor.vue in ./src/router/index.js
* ../components/page/Markdown.vue in ./src/router/index.js
* ../components/page/Upload.vue in ./src/router/index.js
* ../components/page/BaseCharts.vue in ./src/router/index.js
* ../components/page/MixCharts.vue in ./src/router/index.js
* ../components/page/Login.vue in ./src/router/index.js
现在又报这个错了。。。
这些我都有啊

**Comment by lin-xin** [comment]
那么奇怪，你的node版本和npm版本多少

**Comment by oliviazhangjuan** [comment]
node 6.9.1
npm 3.10.8

**Comment by lin-xin** [comment]
你再重新 npm install 看看会不会是哪些漏了

**Comment by oliviazhangjuan** [comment]
我没有翻墙，也没有用淘宝镜像，会不会因为这个问题

**Comment by lin-xin** [comment]
试试 npm install ，哪些装不上会在最下面有报错或警告的

**Comment by oliviazhangjuan** [comment]
报错的我都重新单独安装了

**Comment by lin-xin** [comment]
安装了还会报错吗

**Comment by oliviazhangjuan** [comment]
重新安装都不会有报错了

**Comment by oliviazhangjuan** [comment]
你安装的时候翻墙了吗

**Comment by lin-xin** [comment]
用windows的，没翻墙，这可能跟网络有关或者 镜像源吧，npm config set registry http://registry.cnpmjs.org
这是配置成http的，默认好像是https的，可能网络慢会下载不了吧

**Comment by oliviazhangjuan** [comment]
好吧，那就奇怪了，我再试试吧，万分感谢
