### ISSUE TITLE
升级 vue3 版本意见征集

### ISSUE THREAD

**Issue by lin-xin** [lin-xin/vue-manage-system#262]
element 原有团队已经不维护了，现在分别有两个仓库在对 element 进行 vue 3 版本化，分别是 [element-plus](https://github.com/element-plus/element-plus/) 和 [element3](https://github.com/kkbjs/element3) ，如果两个都上线，版本就会有点乱了。
ant-design-vue 目前已经发布了 vue3 版本的，作者在想支持 vue3 的版本改用 ant-design-vue ，在新分支上进行升级，不知大家怎么看？！

**Comment by chenbaba** [comment]
好想选antd 但是我不会 ...elementui吧

**Comment by TommyFreya** [comment]
都行，学就是了

**Comment by kyle2cj** [comment]
换吧，这次不换，下次还要问换不换？

**Comment by daocaorengax** [comment]
换吧,都学下不是坏事

**Comment by ZhaiXiaoyuan** [comment]
觉得antd好用就换吧，学习成本也还好

**Comment by laoliya** [comment]
关键是换了组件之后还会有多少人选择

**Comment by dreamgo88** [comment]
换吧，ant-design-vue是大势所趋，挡不住的

**Comment by a6336747** [comment]
感觉element越来越乱了,未来堪忧,ant-design-vue是趋势,支持更换

**Comment by crush2020** [comment]
可以换一手，多学习学习吧！

**Comment by learnzpk** [comment]
换吧

**Comment by DarrenYing** [comment]
支持换！

**Comment by eddyyuen** [comment]
用  element-plus

**Comment by wgxg777** [comment]
新起一个项目吧

**Comment by fanhua1994** [comment]
element不更新啥意思。element-ui?

**Comment by lin-xin** [comment]
即将升级到 vue3 + element-plus

**Comment by lin-xin** [comment]
当前已升级到vue3，仍然用的是选项式api，接下来将升级为 组合式api

**Comment by yaoxingpu** [comment]
> element 原有团队已经不维护了，现在分别有两个仓库在对 element 进行 vue 3 版本化，分别是 [element-plus](https://github.com/element-plus/element-plus/) 和 [element3](https://github.com/kkbjs/element3) ，如果两个都上线，版本就会有点乱了。
> ant-design-vue 目前已经发布了 vue3 版本的，作者在想支持 vue3 的版本改用 ant-design-vue ，在新分支上进行升级，不知大家怎么看？！

element plus

**Comment by jamespch** [comment]
这个框架是我用的最合适的框架, 就走vue+element解决方案的路线, vue2--element   vue3--element-plus; 挺好的

**Comment by xyyxhcj** [comment]
antd差不多的

**Comment by sujiewen** [comment]
把这个库 升级到 vue3 .2，element-plus 2.1.0，感觉问题比较多
