### ISSUE TITLE
关于http-proxy-middleware

### ISSUE THREAD

**Issue by 547437352** [lin-xin/vue-manage-system#27]
请问您项目中用到的这个转发插件应该怎么配置呢！本地起来是8000端口，接口端口是8080端口，应该怎么配置才不跨域呢！

**Comment by lin-xin** [comment]
`
proxyTable: {
            '/api':{
                target:'http://localhost:8080',
                changeOrigin:true,
                pathRewrite:{
                    '/api':''
                }
            }
        }
`

**Comment by 547437352** [comment]
今天按照您的说法，进行了修改，发现还是跨域，请您看看我哪里修改错了，或者还需要做什么？
![qq 20170425093245](https://cloud.githubusercontent.com/assets/13287603/25365398/fe7c7788-299a-11e7-9adf-aa5e11ad981b.png)  这是我的接口文档，我接口就在本地！   
![qq 20170425093511](https://cloud.githubusercontent.com/assets/13287603/25365412/184b3c80-299b-11e7-9047-0b870e98481a.png)   这是按照您修改之后的！  
![qq 20170425093548](https://cloud.githubusercontent.com/assets/13287603/25365427/2dd114da-299b-11e7-8af0-2938c5290d8d.png)  这是我请求的方式  
![12312312133131231](https://cloud.githubusercontent.com/assets/13287603/25365457/65f4b164-299b-11e7-9b63-0e9bc06bdd07.png)    这是dev-server 没有做任何修改

![qq 20170425093641](https://cloud.githubusercontent.com/assets/13287603/25365440/39acaf9e-299b-11e7-9f37-36c9922762a7.png)   这是接口报跨域的最后结果  
 
@lin-xin

**Comment by lin-xin** [comment]
@547437352 我配置里写的 /api 是表示匹配接口以 /api 开头的，而你里面的接口是以 /holdseat 开头的，你可以试试这样
proxyTable: { '/holdseat ':{ target:'http://localhost:8080', changeOrigin:true } }

**Comment by 547437352** [comment]
![22222222222222222](https://cloud.githubusercontent.com/assets/13287603/25366353/aa8df8a2-29a1-11e7-85a4-44b84aa7e47e.png)   这样改还是跨域，刚才叫后台来调试，说新增的内容都能介绍到，但是sessionid接收不到！我在想是不是跨域的时候是不允许携带cookie的
@lin-xin

**Comment by lin-xin** [comment]
如果跨域怎么可能还接收到数据，报错信息我看看

**Comment by 547437352** [comment]
![1232132132132132131](https://cloud.githubusercontent.com/assets/13287603/25366762/5dd9107a-29a4-11e7-9a34-8f51c016c2ff.png)
这是报错信息，跨域
![default](https://cloud.githubusercontent.com/assets/13287603/25366771/721d47ae-29a4-11e7-9729-133aa67d5826.png)  这是发出的请求，把需要传递的参数传过去了，后台说能收到传过去的数据
![9999](https://cloud.githubusercontent.com/assets/13287603/25366784/8abff23e-29a4-11e7-911d-dfb2761972c7.png)    这是后台返回的码，约定9999是错误！
![default](https://cloud.githubusercontent.com/assets/13287603/25366793/9b0c2270-29a4-11e7-98a6-ca58fd0d8bd4.png)    这是后台报错信息  ！sessionid收不到！

我刚才实验了，就是不用您的方式，直接按照没有问您以前，npm install下来的方式访问，请求也是能发出去的
@lin-xin

**Comment by lin-xin** [comment]
你不配置代理，不是能请求成功吗？那就不需要代理啊。。。
至于你们sessionid传不过去，你们前端怎么传，后台怎么接收，这我帮不了你们。

**Comment by 547437352** [comment]
好吧，感谢

**Comment by 547437352** [comment]
![0](https://cloud.githubusercontent.com/assets/13287603/25371786/fbd28dd6-29c4-11e7-9bd1-a48f3c551f1d.png)  我尝试写成了这样，
![default](https://cloud.githubusercontent.com/assets/13287603/25371802/1ae286fe-29c5-11e7-805d-fce03cef078d.png)   把接口文件的8080，改成了8000，就可以了应该是他收到  holdseat/这样的请求，虽然请求的是8000，他会把8000转发了8080上面去，8080接收到数据，然后http-proxy-middleware再把数据转发到我8000上面去！

分享出来让issues的人看到
