### ISSUE TITLE
如何开启浏览器图标？

### ISSUE THREAD

**Issue by Rurouni-z** [lin-xin/vue-manage-system#273]
为什么public/index.html设置了没有用 求大神帮助
<link rel ="shortcut icon" type="image/x-icon" href="static/favicon.ico">

**Comment by Z-timer** [comment]
出来了  可能我电脑卡了= =

**Comment by pfzhen** [comment]
图标的地址改成http的就好了

**Comment by sayid760** [comment]
已收到了···
