### ISSUE TITLE
npm run dev error too

### ISSUE THREAD

**Issue by Veitor** [lin-xin/vue-manage-system#28]
![image](https://cloud.githubusercontent.com/assets/7483890/25425778/9e7523f2-2a9f-11e7-8704-7b3747ca15a3.png)
我也出现npm run dev的错误，看截图，啥原因啊，npm install也是成功的啊

**Comment by lin-xin** [comment]
这截图上没有报错的原因啊。用的node 和npm是哪个版本的啊

**Comment by Veitor** [comment]
node 5.10.1
npm 4.5.0
和版本有关系？

**Comment by lin-xin** [comment]
我更新了 package.json 里的modules版本，可更新后尝试是否可以运行。该issue将会关闭，如有问题，可重开。
