### ISSUE TITLE
关于 require('fs)模块的问题！

### ISSUE THREAD

**Issue by bugs1111** [lin-xin/vue-manage-system#30]
因为我使用到了模块`ws`，他其中有`var fs = require('fs')`加载`fs`模块使用的部分。
然后每次`npm run dev`的时候，在编译期间，总是会报错如下：
~~~
ERROR  Failed to compile with 1 errors
This dependency was not found:

* fs in ./src/main.js

To install it, you can run: npm install --save fs
~~~

即使我安装模块`fs`他仍然报错。

网上有类似的解决方法，在webpack的配置文件中加入`fs: empty`来忽略这个错误，但貌似忽略来后，fs就无法正常使用来。

求大神给他解决方法～

---
下面是我的测试代码：
~~~javascript
import Vue from 'vue';
import App from './App';
import router from './router';
import axios from 'axios';
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-default/index.css';    // 默认主题
// import '../static/css/theme-green/index.css';       // 浅绿色主题
import "babel-polyfill";
import './mock/index.js';

import fs from 'fs';  // 我加入的测试代码

Vue.use(ElementUI);
Vue.prototype.$axios = axios;
new Vue({
    router,
    render: h => h(App)
}).$mount('#app');
~~~

**Comment by bugs1111** [comment]
应该与服务器渲染有关，防止加载错误的组件。
那我现在如果要用这些组件，应该使用在什么地方才是正确的使用方法呢？

**Comment by lin-xin** [comment]
@bugs1111 我看了这个fs的模块，从npm安装下来里面根本就没代码的。

**Comment by bugs1111** [comment]
@lin-xin `fs`是node的内部组件，就类似`os`组件一样。
我网上查过相关文档，如果需要做后端访问，可以增加一组由`express`的后端`server`，通过他就可以访问到包括：数据库，文件，ws等等其他后端组件了！
参考的[博文地址](http://www.jianshu.com/p/00dee32ac150)

**Comment by lin-xin** [comment]
import fs from 'fs';
这样是从node_modules里面去找这个模块的。所以就报上面的错误了。我也不清楚你那个要怎么使用
