### ISSUE TITLE
element-plus版本升级后菜单乱了

### ISSUE THREAD

**Issue by xjieinfo** [lin-xin/vue-manage-system#307]
element-plus在1.0.2-beta.52版本下一切正常，升级到最新的1.1.0-beta.7后，菜单显示不正常，主要是多级菜单，有些没显示，也没有了层次

**Comment by lewishuang14** [comment]
是因为element-plus的菜单组建改名了

**Comment by xjieinfo** [comment]
收到，谢谢

**Comment by xjieinfo** [comment]
Sidebar.vue中将el-submenu改成el-sub-menu，问题解决，再次感谢！
