### ISSUE TITLE
路由缓存问题。

### ISSUE THREAD

**Issue by CYscared** [lin-xin/vue-manage-system#309]
场景： 详情页或者编辑页只有路由参数不同，/article/:id或者/article?id=123（后台管理常用）。
问题：页面打开多个编辑页，tags标签上切换页面，页面缓存数据都是一样的（vue相同组件，无法缓存多个页面状态吧）。

> 
          <keep-alive :include="tagsList">
            <router-view />
          </keep-alive>

看到很多以前的管理后台系统标签上出现多个编辑页(id不同)，页面表单数据可以不同，当然都是前后端不分离的老项目，vue管理后台，不知道能不能实现，刚需啊。。。求解答

**Comment by z790490122** [comment]
估计不能用keep-alive去保持了,tagesList里面写的name.

可以换个思路,动态生成个tabs
https://element-plus.gitee.io/#/zh-CN/component/tabs

**Comment by CYscared** [comment]
> 估计不能用keep-alive去保持了,tagesList里面写的name.
> 
> 可以换个思路,动态生成个tabs
> https://element-plus.gitee.io/#/zh-CN/component/tabs

多谢建议，哎，上家公司同事的项目用的vue-manage-system，发现这个缓存被他给删除了，不做缓存，不知道是什么原因，现在自己的项目实际用了一下，真的是问题好大。。。作者项目中的案例可能没有考虑到传参的时候出现的bug，百度发现好多人都遇到了，没有什么好的解决方案，你这个动态tabs倒是有机会。

**Comment by CYscared** [comment]
> 估计不能用keep-alive去保持了,tagesList里面写的name.
> 
> 可以换个思路,动态生成个tabs
> https://element-plus.gitee.io/#/zh-CN/component/tabs

完美解决，留言给其他的小伙伴看到
