### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by cybibo** [lin-xin/vue-manage-system#31]
$npm run build
....
ERROR in static/js/0.ed314fa45c35f2165374.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/0.ed314fa45c35f2165374.js:13189,6]
.....
Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

**Comment by lin-xin** [comment]
@cybibo 压缩失败，还能运行吗。该文件是不是 vue-core-image-upload 这个插件的压缩文件呢

**Comment by lin-xin** [comment]
这应该是这个插件里用了es6的写法才会在压缩的时候失败。可以卸载掉安装回他旧版本插件，旧的应该没问题。

**Comment by tingyuji** [comment]
这个问题我也遇到了，我把 vue-core-image-upload 去掉换成其他同功能组价就完事
