### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by hbsndg** [lin-xin/vue-manage-system#32]
npm install正常，但是npm run dev就报错

ERROR  Failed to compile with 1 errors                                                                         10:16:00

 error  in ./~/vue-core-image-upload/src/props.js

Module parse failed: E:\study\project\github\vue-manage-system\node_modules\vue-core-image-upload\src\props.js Unexpected token (46:13)
You may need an appropriate loader to handle this file type.
|   ResizeBtn: {
|     type: Object,
|     default: return {
|       ok: 'Ok',
|       cancel: 'Cancel'

 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-core-image-upload/src/vue-core-image-upload.vue 49:13-31
 @ ./~/vue-core-image-upload/src/vue-core-image-upload.vue
 @ ./~/vue-core-image-upload/src/index.js
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/page/Upload.vue
 @ ./src/components/page/Upload.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client babel-polyfill ./src/main.js

**Comment by lin-xin** [comment]
这是 vue-core-image-upload 插件版本升级引起的

**Comment by lin-xin** [comment]
卸载掉后 npm i vue-core-image-upload@2.1.5 -S ，安装2.1.5版本的即可。官方的新版本有bug
