### ISSUE TITLE
Linux下安装好后，npm run dev后访问页面报错

### ISSUE THREAD

**Issue by qmzorvim123** [lin-xin/vue-manage-system#326]
![image](https://user-images.githubusercontent.com/46865239/149860350-ed8c65cb-4459-46b1-a3d1-5c0a403d9545.png)
![image](https://user-images.githubusercontent.com/46865239/149860445-ebd455d9-f03c-490a-9924-535f1c76554b.png)

**Comment by qmzorvim123** [comment]
可以了 先cd vue-manage-system/
然后npm run build再npm run serve后 就有页面了

**Comment by sayid760** [comment]
已收到，请放心···
