### ISSUE TITLE
您好，在config/index.js中配置proxyTable,无法生效

### ISSUE THREAD

**Issue by xiaoxintiaoda** [lin-xin/vue-manage-system#33]
`proxyTable: {
            '/manager':{
                target:'http://manager.xxxxxx.com',
                changeOrigin:true,
                pathRewrite:{
                    '^/manager':'/manager'
                }
            }
        },`
这样配置的的，但是并不生效。所以想问一下，这个框架支持使用proxyTable吗

**Comment by lin-xin** [comment]
支持的。配置也没错。你确认你接口以 /manager 开头，路径没错吗。
pathRewrite 是重写接口里的  /manager 为  /manager。真实接口没错吗？

**Comment by xiaoxintiaoda** [comment]
额....其实我是写后端的，对前端不太熟，本来是打算用这个框架做后台管理系统的页面，我们以前都是混着写，很乱也很麻烦，但是我用的时候发现要学好多东西我都不会，所以我还是先学了再来吧，我先把这个关掉吧，也许是我自己没配好..
