### ISSUE TITLE
element的使用

### ISSUE THREAD

**Issue by gudaonanfeng** [lin-xin/vue-manage-system#333]
我是用element-plus官网上的组件复制进去提示报错，然后我更新element-plus也是报错，请问如何解决呢

**Comment by sayid760** [comment]
已收到，请放心···

**Comment by gudaonanfeng** [comment]
已经解决，方法是将更新 vite 版本后解决；原版本vite：2.3.7升级到 vite：2.6.13，然后运行npm run dev还是报错，提示没有找到文件，执行node ./node_modules/esbuild/install.js后即可解决，可以正常加载elementplus组件
