### ISSUE TITLE
如何在内容页中跳转页面？

### ISSUE THREAD

**Issue by javakevin1** [lin-xin/vue-manage-system#336]
this.$router.push(地址);类似这样的无法实现页面的调整，问一下要怎么做呢

**Comment by xiaoguaishou1** [comment]
能详细说一下是vue2版本 还是vue3呢  ?
有报错信息吗

**Comment by xiaoguaishou1** [comment]
> this.$router.push(地址);类似这样的无法实现页面的调整，问一下要怎么做呢
