### ISSUE TITLE
当前仓库代码并非最新版本，望管理员检查

### ISSUE THREAD

**Issue by 55567772** [lin-xin/vue-manage-system#337]
我下载的是当前仓库的代码，但并非最新版本，请检查。谢谢。
还有，这个项目我觉得可以做得更好，目前功能还是少了些，希望大家可以多多赞助。

**Comment by bailuochen** [comment]
确实不是最新代码

**Comment by liliewin** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
