### ISSUE TITLE
基础表格页面搜索功能无效

### ISSUE THREAD

**Issue by Drewolf** [lin-xin/vue-manage-system#338]
基础表格页面搜索功能没有效果，点击搜索没反应

**Comment by Yutti7** [comment]
这也要提？

**Comment by LR-alt** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lin-xin/vue-manage-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 下午4:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [lin-xin/vue-manage-system] 基础表格页面搜索功能无效 (Issue #338)





 
这也要提？
 
—找个时间修复下吧

**Comment by Yutti7** [comment]
这只是没配置接口而已，你自己改一下不就完了
