### ISSUE TITLE
tag版本5.0.0，依赖安装vue-i18n报错，后面的最好固定版本9.0.0

### ISSUE THREAD

**Issue by Gambler-Wang** [lin-xin/vue-manage-system#346]

**Comment by Gambler-Wang** [comment]
安装tag版本依赖时，vue-i18n报错，导致项目无法正常运行，最后固定vue-i18n@9.0.0版本才得以正常运行。
建议后面的依赖如有必要可以固定版本

**Comment by lin-xin** [comment]
谢谢建议。考虑到i18n在实际后台管理项目中较少用到，已在最新版本中移除
