### ISSUE TITLE
在该项目中为什么不直接注册v-head的组件，而是用vHead组件

### ISSUE THREAD

**Issue by tingyuji** [lin-xin/vue-manage-system#36]
如果注册组件用v-head，这样就不会造成更多的误解，请解释下，谢谢

**Comment by lin-xin** [comment]
## 如何提 Issue

使用本项目意味着你也有义务帮助其变得更好。

不要浪费维护者时间。

不要让维护者帮你学习Vue，帮你熟悉vue-loader，甚至帮你写代码。

不要认为随便一句话就能让维护者明白你的意思，我们没有你想象的那么厉害。

不要提没有任何意义的、代码中带有业务逻辑不方便重现的Issue。

直接关闭你的issue不是对你不满，是你提问题方式不对，没有必要再浪费时间说明为什么要关闭你的issue。
