### ISSUE TITLE
部署到本地环境后，也页面变形混乱

### ISSUE THREAD

**Issue by Kaige3** [lin-xin/vue-manage-system#387]
![image](https://github.com/lin-xin/vue-manage-system/assets/129776158/c2f92807-2e7e-4668-b54a-22cf3908252d)
![屏幕截图 2024-05-22 152634](https://github.com/lin-xin/vue-manage-system/assets/129776158/4958f7f1-e73d-4a9b-9c86-8a5244d441d3)

**Comment by sober3125** [comment]
![image](https://github.com/lin-xin/vue-manage-system/assets/129776158/2d83d982-c6a8-4913-96da-22998cf255b1)
![image](https://github.com/lin-xin/vue-manage-system/assets/129776158/ec78549f-a55f-46a7-aa48-5a110a27507c)
