### ISSUE TITLE
启动时警告

### ISSUE THREAD

**Issue by Georgepentaho** [lin-xin/vue-manage-system#39]
启动后首次登陆会出现如下警告信息，是否可以忽略：

 warning  in ./src/components/common/Sidebar.vue

(Emitted value instead of an instance of Error) <el-menu-item v-for="subItem in
item.subs">: component lists rendered with v-for should have explicit keys. See
https://vuejs.org/guide/list.html#key for more info.

 @ ./src/components/common/Sidebar.vue 9:2-186
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src
/components/common/Home.vue
 @ ./src/components/common/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client babel-polyfill ./src/main.js

**Comment by lin-xin** [comment]
@Georgepentaho 已修复该警告，可以重新pull。原因在 vue2.2+使用v-for循环组件，需要指定一个key。
