### ISSUE TITLE
Q：表格分页代码

### ISSUE THREAD

**Issue by Georgepentaho** [lin-xin/vue-manage-system#40]
能不能把BaseTable.vue中分页代码总的页数不写死，而从API读取：
<el-pagination @current-change="handleCurrentChange" layout="prev, pager, next" :total="100">
中 :total="100"

**Comment by lin-xin** [comment]
@Georgepentaho 这个可以啊。我这里只是个例子。你根据实际使用啊。

**Comment by Georgepentaho** [comment]
恩，谢谢！
