### ISSUE TITLE
启动时，console报错

### ISSUE THREAD

**Issue by runningmaverick** [lin-xin/vue-manage-system#43]
Error in event handler for (unknown): TypeError: Cannot read property 'status' of null  :8080/#/login:1 

没有错误栈

浏览器版本：chrome 58

**Comment by lin-xin** [comment]
npm 打印什么错误信息

**Comment by runningmaverick** [comment]
npm没有错误信息

**Comment by lin-xin** [comment]
发截图啊，这样无法定位你的错误。你自己有没有尝试找问题呢？

**Comment by runningmaverick** [comment]
<img width="1303" alt="wx20170523-120338 2x" src="https://cloud.githubusercontent.com/assets/17487729/26338066/f0835b12-3faf-11e7-8f10-3c27e9bc8785.png">

用的最新master代码， npm run dev

没有错误栈，也不是从引入的js代码中报的，你那没有这个问题？

**Comment by lin-xin** [comment]
我这边不会，看上面的端口是8082？有改动过代码吗？

**Comment by runningmaverick** [comment]
和别的服务冲突，config/index.js 中的8080改成了8082，其他未修改

**Comment by lin-xin** [comment]
只改端口不会造成影响。要么你把你的项目文件发给我，我调调看。qq:2981207131
