### ISSUE TITLE
请问这个proxy是干什么的，跨域请求吗

### ISSUE THREAD

**Issue by yanqi321** [lin-xin/vue-manage-system#45]
![image](https://cloud.githubusercontent.com/assets/22360047/26408447/67331a56-40d0-11e7-9647-d4d10fdf72c6.png)

**Comment by lin-xin** [comment]
可以这样理解。这个是在服务端配置代理，通过服务端去请求接口，而不是前端去请求，这样就不会有跨域的问题。
