### ISSUE TITLE
如何更改头部的信息

### ISSUE THREAD

**Issue by luocongjay** [lin-xin/vue-manage-system#47]
比如，我在page页里面获取到用户的头像，想更新到header里面的头像，请问怎么做才可以实现呢？
网上查很多都是vuex，就是请问下还有没有其他方法。谢谢~

**Comment by lin-xin** [comment]
用vuex就比较方便在不同组件间通讯，你不用vuex，那就先传给父组件，父组件再传给另外一个组件咯
