### ISSUE TITLE
关于webpack的DllPlugin 和 DllReferencePlugin

### ISSUE THREAD

**Issue by joneqian** [lin-xin/vue-manage-system#53]
我clone你的工程，并去掉DllPlugin 和 DllReferencePlugin的注释，怎么比不用DllPlugin 和 DllReferencePlugin编译还慢呢？？

**Comment by lin-xin** [comment]
请将webpack.dll.conf.js 里的 vue-echarts-v3 去掉再重新编译。这个插件在项目中我已经不用了，这个体积很大导致慢了很多。
