### ISSUE TITLE
npm install 安装不了依赖 

### ISSUE THREAD

**Issue by zhengjianli126** [lin-xin/vue-manage-system#55]
我npm 版本是3.10.10  node 是6.11.0 是不是有问题

**Comment by Guxinpei** [comment]
亲测没问题朋友，试试cnpm？

**Comment by yunshang** [comment]
我也遇到一样的问题

**Comment by jiezaichan** [comment]
我也遇到了 提示url-parse@1.4.3安装不了
去package-lock.json把url-parse删掉再次npm install即可 
楼上可以参考
