### ISSUE TITLE
如何让图中的可视化图表随着屏幕大小而变化呢？

### ISSUE THREAD

**Issue by Jupiter-Lee** [lin-xin/vue-manage-system#59]
![image](https://user-images.githubusercontent.com/20852883/29306301-85002c6e-81cf-11e7-89c0-cacc60f67d36.png)
现在的情况是页面空间变小之后就会出现滚动条（如上图）

**Comment by lin-xin** [comment]
现在是写死的宽高，就会这样。你要自适应的话，你要自己调用vue中 this.$set() 去修改宽高传给 vue-schart 组件，组件会监听宽高变化重新渲染

**Comment by Guxinpei** [comment]
不建议用自适应朋友，之前我碰到了个坑，整体宽高自适应的话，你还需要考虑里面的每一款引用的第三方是不是支持（恰好我的项目里用到了一个新手封的组件），毕竟是个管理端，不必须的话还是不要坑自己了。

**Comment by Jupiter-Lee** [comment]
公司要用，我先试试吧
