### ISSUE TITLE
为什么打包后Css 没有打包成一个文件?

### ISSUE THREAD

**Issue by cybibo** [lin-xin/vue-manage-system#60]
这是我打包后的源码：
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>manage-system</title>
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
<meta name="keywords" content="vue.js, wms, vue2, 后台模板, 管理系统, element" />
 <meta name="description" content="基于Vue2 + Element UI 的后台管理系统解决方案" />
 </head>
<body>
<div id="app"></div>
 <script src="./static/js/vendor.dll.js"></script>
<script type="text/javascript" src="/app.js"></script></body>
</html>

这是你线上(http://open.omwteam.com/work/#/login)打包后的源码:

<!DOCTYPE html><html>
<head><meta charset=utf-8>
<title>manage-system</title>
<meta name=viewport content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
<meta name=keywords content="vue.js, wms, vue2, 后台模板, 管理系统, element">
<meta name=description content="基于Vue2 + Element UI 的后台管理系统解决方案">
<link href=./static/css/app.260fd38757c8d00ad9ef739ca97bb2c9.css rel=stylesheet>
</head>
<body>
<div id=app></div>
<script type=text/javascript src=./static/js/manifest.5e485a363fe34070cff2.js></script>
<script type=text/javascript src=./static/js/vendor.b7f323ffc6b03b5d803f.js></script>
<script type=text/javascript src=./static/js/app.42d94365fe1a11281cba.js></script>
</body>
</html>

我也想打包成如你线上的源码，我在webpack配置里怎么改?

**Comment by lin-xin** [comment]
@cybibo 请参考 https://github.com/lin-xin/blog/issues/10

**Comment by cybibo** [comment]
不好意思，我还是没找到如何把CSS打包成一个CSS的解决办法，在webpack.prod.conf.js里有
new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
但运行npm run build之后，打包后的列表没看到生成css文件。

**Comment by lin-xin** [comment]
抱歉我上面误解你的意思了。

写在 .vue 文件里的用 style标签写的css ,打包后会以 style 标签在 head 插入。通过 import css 文件，则会把文件打包成一个css文件在head引入。你看你是怎么写的呢！
