### ISSUE TITLE
期待你的回复，需要你的指点一二

### ISSUE THREAD

**Issue by 15826954460** [lin-xin/vue-manage-system#61]
大神！为什么你的线上地址访问不了，而且sChart学习网址也访问不了！想边看你的demo效果图，边敲代码，再学习你的代码，这个看不了线上地址，有点难啊！

**Comment by lin-xin** [comment]
旧的服务器到期了，都换了新的地址。在github上仓库里的都是新的地址。
http://open.omwteam.com/work 
schart 的文档地址 http://open.omwteam.com/sChart/index.html

**Comment by 15826954460** [comment]
问题已解决，谢谢你的回复
