### ISSUE TITLE
为什么clone下来安装依赖运行就报 Exited with code 3

### ISSUE THREAD

**Issue by zuoguojun** [lin-xin/vue-manage-system#62]
node build/dev-server.js

[HPM] Proxy created: /api  ->  http://jsonplaceholder.typicode.com
[HPM] Proxy rewrite rule created: "/api" ~> ""
[HPM] Proxy created: /ms  ->  https://www.easy-mock.com/mock/592501a391470c0ac1fab128
_(node:21159) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3_

 DONE  Compiled successfully in 9259ms                                                                     10:24:12 AM

> Listening at http://localhost:8080

运行环境为阿里云centos6.5服务器，在windows环境下访问ip:8080，没有反应。
在windows环境下直接报找不到watchpack的错误

node新手，在给公司找一个管理后台，上来就碰到问题了

**Comment by lin-xin** [comment]
这个错误听说是最新版的node.js报的，可以换个旧的稳定版本试试吧。
没有反应控制台有报什么错吗
