### ISSUE TITLE
关于权限是怎么处理的

### ISSUE THREAD

**Issue by Alan201601** [lin-xin/vue-manage-system#64]
你好，我们团队现在也在考虑使用vue+elementui 重新构建之前的系统，现在想了解一下你们的系统在权限控制方面是怎么做的，后台是java。

**Comment by yasinshaw** [comment]
你好，我做了一套权限系统，基于用户-角色-serviceAPI的。自己实现的，基于aop，十分轻量级(只使用了了User,Role, ServiceMethod三个实体类+一个@PublicAPI注解，一个aspect用于判断权限)。后端是java，框架是springboot，数据对接协议是json-rpc(你要使用restful也可以的)。
整个框架可以实现Service方法级别的权限控制，可以和我交流哦。qq245556547~

**Comment by klren0312** [comment]
他这系统就是简单演示用的。。。
