### ISSUE TITLE
升级到element UI 2.0.8的时候样式就不对了~

### ISSUE THREAD

**Issue by yurizhang** [lin-xin/vue-manage-system#71]
升级到element UI 2.0.8的时候样式就不对了~
没有办法显示那个黑色主题了，能处理一下吗？

**Comment by lin-xin** [comment]
可以参考 element 官方文档，已经使用了background-color 、text-color、active-text-color 等属性来自定义颜色了，我这边的master分支也已经更新到最新版本的，可以了解一下。
