### ISSUE TITLE
table中的数据展示，其中getDate中self.url的路径找不到具体文件。。。求大神解答。。。

### ISSUE THREAD

**Issue by HeXu1994** [lin-xin/vue-manage-system#77]
getData(){//获取数据
                let self = this;
                if(process.env.NODE_ENV === 'development'){
                    self.url = '/ms/table/list';  // 这里的路径怎么找哇。。。是不是有路由。。。求大神解答
                }
                self.$axios.post(self.url, {page:self.cur_page}).then((res) => {
                    self.loading=false;
                    self.tableData = res.data.list;
                })
            },

**Comment by lin-xin** [comment]
@HeXu1994 这个路径是用 easy-mock 生成的接口，用来模拟数据，可以搜一下 easy-mock 了解一下，改成你自己的接口就有你的数据了
