### ISSUE TITLE
对于tables，如何异步获取数据

### ISSUE THREAD

**Issue by mitboy1983** [lin-xin/vue-manage-system#83]
看例子是一次把所有data全部拉完，然后本地分页，对于真实应用场景，有时候数据量会很大，不可能一次把所有数据全部加载完

这个时候如何在每次分页的时候通过api 请求一次数据 然后在加载本地显示？

可以给个合理方案吗？

**Comment by tfh93121** [comment]
数据量大就不可能通过API请求一次数据，都应该是分页请求的

**Comment by mitboy1983** [comment]
是的就是楼上朋友这个意思，分页请求数据，比如一次加载 20 个

**Comment by tfh93121** [comment]
后续请求到的数据push到data中就好了   视图自己更新的

**Comment by lin-xin** [comment]
@tfh93121 正解，这跟以前ajax分页没什么区别
