### ISSUE TITLE
v2如何更新到V3

### ISSUE THREAD

**Issue by liguoyu** [lin-xin/vue-manage-system#84]
现在用的是V2的，想更新到V3。项目已经做得差不多了，还能更新嘛，会不会有为什么问题？

**Comment by lin-xin** [comment]
项目做得差不多，最好还是做完先。后面有时间再进行优化升级。现在升级，多多少少肯定自己会遇到一些难题的。要升也可以，首先使用最新的config/build等配置文件。其他代码方面，很多都只是新增了而已。那就要自己看看哪些需要了。
