### ISSUE TITLE
请问怎么手动关闭标签(tag)

### ISSUE THREAD

**Issue by fighhin** [lin-xin/vue-manage-system#86]
我遇到了一个问题,由于每个子页面对应一个标签,如果一个标签开始被打开过没有关闭,从其他路由跳转到这个路由时不会执行mounted函数里面的函数刷新数据,然后我用watch属性监听路由变化发现el-table的格式就乱了,所以请问有路由离开当前页面也将这个标签关闭的方法吗

**Comment by fighhin** [comment]
而且由于这个tag的存在,有时候跳转到已经有tag的页面时,由于已经存在这个路由对象,所以这个页面并不会刷新,有些需要每次进入这个页面需要重置的一些变量也并不会重置,请问楼主有什么解决方法吗

**Comment by lin-xin** [comment]
因为使用 keep-alive ,所以就会缓存，可以把这个标签去掉。也可以在页面里的beforeEnter钩子函数里进行重置。

**Comment by fighhin** [comment]
解决了,谢谢

**Comment by sunyajun-git** [comment]
想了解一下怎么实现的,控制当前tab页操作完成后执行关闭

**Comment by lin-xin** [comment]
@sunyajun-git 触发自定义事件 close_current_tags
```
bus.$emit('close_current_tags');
```
