### ISSUE TITLE
请问在标签页如何打开一个新的标签？并且焦点在新开的标签页上面？

### ISSUE THREAD

**Issue by xiaolv899** [lin-xin/vue-manage-system#87]
抱歉；看了文档没发现有这个的说明，望答复，谢谢

**Comment by lin-xin** [comment]
首先在 Tags.vue 里监听路由变化
```js
watch:{
            $route(newValue, oldValue){
                this.setTags(newValue);
            }
        }
```
把新的路由push到一个数组里，这些标签就是这个数据遍历出来的
在template里有 `:class="{'active': isActive(item.path)}"`，根据路由path来匹配，添加这个 active 的类名，获得焦点。

**Comment by xiaolv899** [comment]
好的，谢谢
