### ISSUE TITLE
前后端分离如何实现？

### ISSUE THREAD

**Issue by HelloKevinTian** [lin-xin/vue-manage-system#88]
你好，目前使用您的前端架子搭了一个网站，使用wenpack打包到dist目录，然后放在nginx的静态目录下，后端起了一个node端口服务。请问这种前后分离的姿势对不对，登录时一直有问题，登录出现了一个options 204请求。session貌似也有问题，一个登录用户生成了多份session存档。

请问前后端分离的正确姿势是什么样的？

**Comment by lin-xin** [comment]
@HelloKevinTian 使用wenpack打包到dist目录，然后放在nginx的静态目录下，后端起了一个node端口服务。这个都是一样的。然后登录的时候，我这边使用 JWT ，登录后后端返回一个token 给前端，前端每次请求都把token带在header里传给后端验证。

**Comment by HelloKevinTian** [comment]
已解决
