### ISSUE TITLE
关于后台权限管理菜单展示问题

### ISSUE THREAD

**Issue by mitboy1983** [lin-xin/vue-manage-system#90]
本地搭建了一下源码，对于鉴权是直接钩子上做的，如果没有权限浏览那么就跳403， 有没有办法实现 比如 没有权限的账号登录，那么不让这个栏目出现呢？

因为这个需要权限的页面当没有权限的人看到跳403 还不如直接不显示，有权限的人登录以后才显示

网上看了一些文章都是 基于 vuex 来弄的，有没有不用 vuex 来实现的， 项目太小感觉用vuex太麻烦了

**Comment by lin-xin** [comment]
嗯，首先你的菜单是后台返回的数据还是自己本地写死的。本地的话就需要你自己写判断条件来控制显示隐藏啊，比如说登录后，用户角色role是admin，在菜单那里 v-if="role === 'admin'" 来显示出来。
