### ISSUE TITLE
从tag栏重新打开，如何保持原来路由后带着的参数

### ISSUE THREAD

**Issue by nian1123** [lin-xin/vue-manage-system#92]
原来是这样
![image](https://user-images.githubusercontent.com/25632387/40636670-e4847132-6332-11e8-8454-af8e59ce3261.png)

从tag栏重新打开变这样
![image](https://user-images.githubusercontent.com/25632387/40636698-0d220c6c-6333-11e8-9c76-6803f2897313.png)
怎么样实现重新打开的时候还有这些参数呢？

**Comment by nian1123** [comment]
或者离开该页面的时候如何关闭本tag

**Comment by lin-xin** [comment]
在 Tags.vue 中：
```js
// 设置标签
            setTags(route){
                const isExist = this.tagsList.some(item => {
                    return item.path === route.path;
                })
                !isExist && this.tagsList.push({
                    title: route.meta.title,
                    path: route.path
                })
            },
```

这里用到的 route.path 改成 route.fullpath 即可。
