### ISSUE TITLE
标签页关闭后还是保存在内存中的，再次点击右侧相同的菜单，输入数据没被清掉

### ISSUE THREAD

**Issue by chenbeta** [lin-xin/vue-manage-system#93]
用了keep-alive会保存在内存中，点击关闭当前标签页的时候应该destroy当前加载的组件。

**Comment by lin-xin** [comment]
https://github.com/lin-xin/vue-manage-system/pull/98 已修复

**Comment by pengyinghao** [comment]
> [＃98](https://github.com/lin-xin/vue-manage-system/pull/98)已修复
请问一下  在打开的tags下 动态切换tag 如何保证页面不被刷新呢。在tag下关闭了某一个页面，再打开的时候需要刷新页面
