### ISSUE TITLE
左侧的导航栏不能下拉

### ISSUE THREAD

**Issue by linlvping** [lin-xin/vue-manage-system#94]
在chrome下面观看demo，如果把《表单相关》展开，左侧导航列表增长，但屏幕不能滚动，只能看到当前屏幕高度的内容

**Comment by linlvping** [comment]
chrome版本：版本 66.0.3359.181（正式版本） （64 位）

**Comment by lin-xin** [comment]
https://github.com/lin-xin/vue-manage-system/issues/81
